version: '3.6'

services:
  node:
    container_name: node_1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    networks:
      - codernet

  db:
    container_name: db_1
    restart: always
    image: bitnami/mongodb:4.2
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=c03fFbNW11UgwnWJ
      - MONGODB_USERNAME=juanmavazquez91
      - MONGODB_PASSWORD=c03fFbNW11UgwnWJ
      - MONGODB_DATABASE=coderexample
    networks:
      - codernet

  mail:
    container_name: mail_1
    restart: always
    image: mailhog/mailhog:latest
    ports:
     - "8025:8025"
    networks:
    - codernet

networks:
  codernet:
    driver: "bridge"
