tags:
  - name: Products
    description: Operaciones relacionadas con productos

paths:
  /api/products:
    get:
      summary: Obtener lista de productos
      tags:
        - Products
      responses:
        '200':
          description: Lista de productos obtenida con éxito
          content:
            application/json:
              example:
                status: success
                products:
                  - id: "645c26cd6db46f0e76038fb9"
                    title: Aceite de oliva
                    description: Aceite de oliva virgen extra
                    price: 20
                    thumbnail: aceite.jpg
                    code: AC002
                    stock: 8
                    enabled: true
                  - id: "645c270a6db46f0e76038fbf"
                    title: Huevos
                    description: Huevos frescos de granja
                    price: 20
                    thumbnail: huevos.jpg
                    code: HU005
                    stock: 60
                    enabled: true
                pagination:
                  totalDocs: 24
                  limit: 10
                  totalPages: 3
                  page: 1
                  pagingCounter: 1
                  hasPrevPage: false
                  hasNextPage: true
                  prevPage: null
                  nextPage: 2
        '404':
          description: Productos no encontrados

    post:
      summary: Agregar un nuevo producto
      tags:
        - Products
      requestBody:
        description: Datos del nuevo producto a agregar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      examples:
        example1:
          summary: Ejemplo de solicitud para agregar un producto
          value:
            title: Agua Mineral
            description: Villa del Sur 6 Lt
            price: 400
            code: AGUA01
            stock: 7
      responses:
        '201':
          description: Producto agregado con éxito

/api/products/{pid}:
    get:
      summary: Obtener detalles de un producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: ID del producto a buscar
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalles del producto obtenidos con éxito
        '400':
          description: El ID debe tener una longitud de 24 caracteres
        '404':
          description: Producto no encontrado

    put:
      summary: Actualizar un producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: ID del producto a actualizar
          required: true
          schema:
            type: string
      requestBody:
        description: Nuevos datos del producto
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdate'
      responses:
        '200':
          description: Producto actualizado con éxito
        '400':
          description: El ID debe tener una longitud de 24 caracteres
        '404':
          description: Producto no encontrado

    delete:
      summary: Eliminar un producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: ID del producto a eliminar
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado con éxito
        '400':
          description: El ID debe tener una longitud de 24 caracteres
        '404':
          description: Producto no encontrado

components:
  schemas:
    NewProduct:
      type: object
      properties:
        title:
          type: string
          example: Agua Mineral
        description:
          type: string
          example: Villa del Sur 6 Lt
        price:
          type: number
          example: 19.99
        code:
          type: string
          example: AGUA01
        stock:
          type: number
          example: 10
      required:
        - title
        - description
        - price
        - code
        - stock

    ProductUpdate:
      type: object
      properties:
        title:
          type: string
          example: Yerba Mate Amanda
        price:
          type: number
          example: 3320
        stock:
          type: number
          example: 20